/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hartgerink.thegrid3;

/**
 *
 * @author kevinhartgerink
 */
public class StrokeSettings extends javax.swing.JPanel {
    private float strokeWidth;
    
    /**
     * Creates new form StrokeSettings
     */
    public StrokeSettings() {
        initComponents();
        strokeWidth = 3;
    }
    
    public float getStrokeWidth() {
        return strokeWidth;
    }
    
    private void signal() {
        this.firePropertyChange("Change", false, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStrokeWidth = new javax.swing.JLabel();
        jTextFieldStrokeWidth = new javax.swing.JTextField();
        jSliderStrokeWidth = new javax.swing.JSlider();

        setOpaque(false);

        jLabelStrokeWidth.setText("Stroke Width:");

        jTextFieldStrokeWidth.setColumns(3);
        jTextFieldStrokeWidth.setText("3");

        jSliderStrokeWidth.setMaximum(10);
        jSliderStrokeWidth.setValue(3);
        jSliderStrokeWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStrokeWidthStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSliderStrokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelStrokeWidth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldStrokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStrokeWidth)
                    .addComponent(jTextFieldStrokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderStrokeWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderStrokeWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStrokeWidthStateChanged
        // TODO add your handling code here:
        jTextFieldStrokeWidth.setText(Integer.toString(jSliderStrokeWidth.getValue()));
        strokeWidth = jSliderStrokeWidth.getValue();
        signal();
    }//GEN-LAST:event_jSliderStrokeWidthStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelStrokeWidth;
    private javax.swing.JSlider jSliderStrokeWidth;
    private javax.swing.JTextField jTextFieldStrokeWidth;
    // End of variables declaration//GEN-END:variables
}
