/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hartgerink.thegrid3;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.border.LineBorder;

/**
 *
 * @author kevinhartgerink
 */
public class TheGridGUI extends javax.swing.JFrame {
    private LineBorder gridFocused;
    private LineBorder gridUnFocused;
    
    
    
    /**
     * Creates new form TheGrid
     */
    public TheGridGUI() {
        initComponents();

        //As the jLayeredPane adds jPanel(s), it sets the visiblity of those jPanel(s) to false.
        //To get the desired effect, we need all of them to be visible. This loop itererates though
        //each jPanel in the jLayeredPane and sets the visibility to true.
        for(int i=0; i<jLayeredPaneTools.getComponentCount(); i++) {
            jLayeredPaneTools.getComponent(i).setVisible(true);
        }
        
        jRadioButtonPolygon.doClick();
        
        gridFocused = new LineBorder(Color.black, 3);
        gridUnFocused = new LineBorder(Color.lightGray, 3);   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupToolSelection = new javax.swing.ButtonGroup();
        buttonGroupPolygon = new javax.swing.ButtonGroup();
        jPanelNavigation = new javax.swing.JPanel();
        jLabelZoom = new javax.swing.JLabel();
        jTextFieldZoom = new javax.swing.JTextField();
        jSliderZoom = new javax.swing.JSlider();
        jLabelGridCoordinates = new javax.swing.JLabel();
        jTextFieldGridX = new javax.swing.JTextField();
        jLabelGridY = new javax.swing.JLabel();
        jTextFieldGridY = new javax.swing.JTextField();
        jButtonZeroLocation = new javax.swing.JButton();
        jLabelLastClickonGrid = new javax.swing.JLabel();
        jTextFieldClickGridX = new javax.swing.JTextField();
        jLabelClickGridY = new javax.swing.JLabel();
        jTextFieldClickGridY = new javax.swing.JTextField();
        jLabelClickScreenX = new javax.swing.JLabel();
        jTextFieldClickScreenX = new javax.swing.JTextField();
        jLabelClickScreenY = new javax.swing.JLabel();
        jTextFieldClickScreenY = new javax.swing.JTextField();
        jPanelToolSelection = new javax.swing.JPanel();
        jLabelToolSelection = new javax.swing.JLabel();
        jRadioButtonClick = new javax.swing.JRadioButton();
        jRadioButtonMarker = new javax.swing.JRadioButton();
        jRadioButtonLine = new javax.swing.JRadioButton();
        jRadioButtonPolygon = new javax.swing.JRadioButton();
        jRadioButtonCurve = new javax.swing.JRadioButton();
        jRadioButtonCompass = new javax.swing.JRadioButton();
        jRadioButtonTheGrid = new javax.swing.JRadioButton();
        jLayeredPaneTools = new javax.swing.JLayeredPane();
        jPanelToolsClick = new javax.swing.JPanel();
        jLabelClick = new javax.swing.JLabel();
        jPanelToolsMarker = new javax.swing.JPanel();
        jLabelMarker = new javax.swing.JLabel();
        jPanelToolsLine = new javax.swing.JPanel();
        jLabelLine = new javax.swing.JLabel();
        jPanelToolsPolygon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        colorChooser1 = new com.hartgerink.thegrid3.ColorChooser();
        jCheckBoxShowPolygon = new javax.swing.JCheckBox();
        jCheckBoxShowPolygonRotation = new javax.swing.JCheckBox();
        jCheckBoxShowAnchor = new javax.swing.JCheckBox();
        jSliderRotatePolygon = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonPolygonDeleteFirst = new javax.swing.JButton();
        jButtonPolygonDeleteLast = new javax.swing.JButton();
        jButtonPolygonDeleteAll = new javax.swing.JButton();
        jRadioButtonPolygonAddPoint = new javax.swing.JRadioButton();
        jRadioButtonPolygonMovePoint = new javax.swing.JRadioButton();
        jRadioButtonPolygonSetRotation = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelToolsCurve = new javax.swing.JPanel();
        jLabelCurve = new javax.swing.JLabel();
        jPanelToolsCompass = new javax.swing.JPanel();
        jLabelCompass = new javax.swing.JLabel();
        jPanelToolsTheGrid = new javax.swing.JPanel();
        jLabelTheGrid = new javax.swing.JLabel();
        theGrid = new com.hartgerink.thegrid3.TheGrid();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        jPanelNavigation.setBackground(new java.awt.Color(153, 204, 255));
        jPanelNavigation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelZoom.setText("Zoom:");

        jTextFieldZoom.setColumns(3);
        jTextFieldZoom.setText("20");

        jSliderZoom.setMinimum(1);
        jSliderZoom.setValue(20);
        jSliderZoom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderZoomStateChanged(evt);
            }
        });

        jLabelGridCoordinates.setText("Location X:");

        jTextFieldGridX.setColumns(4);
        jTextFieldGridX.setText("0");

        jLabelGridY.setText("Y:");

        jTextFieldGridY.setColumns(4);
        jTextFieldGridY.setText("0");

        jButtonZeroLocation.setText("Zero");

        jLabelLastClickonGrid.setText("Grid X:");

        jTextFieldClickGridX.setColumns(4);
        jTextFieldClickGridX.setText("0");

        jLabelClickGridY.setText("Y:");

        jTextFieldClickGridY.setColumns(4);
        jTextFieldClickGridY.setText("0");

        jLabelClickScreenX.setText("Screen X:");

        jTextFieldClickScreenX.setColumns(4);
        jTextFieldClickScreenX.setText("0");

        jLabelClickScreenY.setText("Y:");

        jTextFieldClickScreenY.setColumns(4);
        jTextFieldClickScreenY.setText("0");

        javax.swing.GroupLayout jPanelNavigationLayout = new javax.swing.GroupLayout(jPanelNavigation);
        jPanelNavigation.setLayout(jPanelNavigationLayout);
        jPanelNavigationLayout.setHorizontalGroup(
            jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelZoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelGridCoordinates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGridX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGridY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGridY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonZeroLocation)
                .addGap(18, 18, 18)
                .addComponent(jLabelLastClickonGrid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClickGridX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClickGridY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClickGridY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClickScreenX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClickScreenX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClickScreenY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClickScreenY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanelNavigationLayout.setVerticalGroup(
            jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNavigationLayout.createSequentialGroup()
                        .addGroup(jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelZoom)
                                .addComponent(jTextFieldZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldGridX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelGridY)
                                .addComponent(jTextFieldGridY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelGridCoordinates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonZeroLocation)
                                .addComponent(jLabelLastClickonGrid)
                                .addComponent(jTextFieldClickGridX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelClickGridY)
                                .addComponent(jTextFieldClickGridY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelClickScreenX)
                                .addComponent(jTextFieldClickScreenX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelClickScreenY)
                                .addComponent(jTextFieldClickScreenY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelNavigationLayout.createSequentialGroup()
                        .addComponent(jSliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanelToolSelection.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolSelection.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolSelection.setPreferredSize(new java.awt.Dimension(150, 235));

        jLabelToolSelection.setText("Tool Selection: ");

        buttonGroupToolSelection.add(jRadioButtonClick);
        jRadioButtonClick.setText("Click");
        jRadioButtonClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClickActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonMarker);
        jRadioButtonMarker.setText("Marker");
        jRadioButtonMarker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMarkerActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonLine);
        jRadioButtonLine.setText("Line");
        jRadioButtonLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLineActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonPolygon);
        jRadioButtonPolygon.setText("Polygon");
        jRadioButtonPolygon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPolygonActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonCurve);
        jRadioButtonCurve.setText("Curve");
        jRadioButtonCurve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCurveActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonCompass);
        jRadioButtonCompass.setText("Compass");
        jRadioButtonCompass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompassActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonTheGrid);
        jRadioButtonTheGrid.setText("The Grid");
        jRadioButtonTheGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTheGridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolSelectionLayout = new javax.swing.GroupLayout(jPanelToolSelection);
        jPanelToolSelection.setLayout(jPanelToolSelectionLayout);
        jPanelToolSelectionLayout.setHorizontalGroup(
            jPanelToolSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolSelectionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelToolSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonClick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMarker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPolygon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCurve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCompass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTheGrid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelToolSelectionLayout.setVerticalGroup(
            jPanelToolSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelToolSelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonClick)
                    .addComponent(jRadioButtonMarker)
                    .addComponent(jRadioButtonLine)
                    .addComponent(jRadioButtonPolygon)
                    .addComponent(jRadioButtonCurve)
                    .addComponent(jRadioButtonCompass)
                    .addComponent(jRadioButtonTheGrid))
                .addContainerGap())
        );

        jLayeredPaneTools.setBackground(new java.awt.Color(255, 255, 204));
        jLayeredPaneTools.setSize(new java.awt.Dimension(254, 631));

        jPanelToolsClick.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsClick.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsClick.setMaximumSize(new java.awt.Dimension(250, 630));
        jPanelToolsClick.setMinimumSize(new java.awt.Dimension(250, 630));
        jPanelToolsClick.setPreferredSize(new java.awt.Dimension(250, 630));
        jPanelToolsClick.setSize(new java.awt.Dimension(250, 630));

        jLabelClick.setText("Click");

        javax.swing.GroupLayout jPanelToolsClickLayout = new javax.swing.GroupLayout(jPanelToolsClick);
        jPanelToolsClick.setLayout(jPanelToolsClickLayout);
        jPanelToolsClickLayout.setHorizontalGroup(
            jPanelToolsClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsClickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClick)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanelToolsClickLayout.setVerticalGroup(
            jPanelToolsClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsClickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClick)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        jPanelToolsMarker.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsMarker.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsMarker.setMaximumSize(new java.awt.Dimension(250, 630));
        jPanelToolsMarker.setPreferredSize(new java.awt.Dimension(250, 630));
        jPanelToolsMarker.setSize(new java.awt.Dimension(250, 630));

        jLabelMarker.setText("Marker");

        javax.swing.GroupLayout jPanelToolsMarkerLayout = new javax.swing.GroupLayout(jPanelToolsMarker);
        jPanelToolsMarker.setLayout(jPanelToolsMarkerLayout);
        jPanelToolsMarkerLayout.setHorizontalGroup(
            jPanelToolsMarkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsMarkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMarker)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanelToolsMarkerLayout.setVerticalGroup(
            jPanelToolsMarkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsMarkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMarker)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        jPanelToolsLine.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsLine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsLine.setMaximumSize(new java.awt.Dimension(250, 630));
        jPanelToolsLine.setPreferredSize(new java.awt.Dimension(250, 630));
        jPanelToolsLine.setSize(new java.awt.Dimension(250, 630));

        jLabelLine.setText("Line");

        javax.swing.GroupLayout jPanelToolsLineLayout = new javax.swing.GroupLayout(jPanelToolsLine);
        jPanelToolsLine.setLayout(jPanelToolsLineLayout);
        jPanelToolsLineLayout.setHorizontalGroup(
            jPanelToolsLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsLineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLine)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanelToolsLineLayout.setVerticalGroup(
            jPanelToolsLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsLineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLine)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        jPanelToolsPolygon.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsPolygon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsPolygon.setMaximumSize(new java.awt.Dimension(250, 630));
        jPanelToolsPolygon.setPreferredSize(new java.awt.Dimension(250, 630));
        jPanelToolsPolygon.setRequestFocusEnabled(false);
        jPanelToolsPolygon.setSize(new java.awt.Dimension(250, 630));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Polygon");

        jCheckBoxShowPolygon.setSelected(true);
        jCheckBoxShowPolygon.setText("Show Polygon");
        jCheckBoxShowPolygon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPolygonActionPerformed(evt);
            }
        });

        jCheckBoxShowPolygonRotation.setText("Show Rotation");
        jCheckBoxShowPolygonRotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPolygonRotationActionPerformed(evt);
            }
        });

        jCheckBoxShowAnchor.setText("Show Anchor");
        jCheckBoxShowAnchor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowAnchorActionPerformed(evt);
            }
        });

        jSliderRotatePolygon.setMaximum(360);
        jSliderRotatePolygon.setValue(0);
        jSliderRotatePolygon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRotatePolygonStateChanged(evt);
            }
        });

        jLabel2.setText("Rotation Slider:");

        jTextField1.setColumns(3);
        jTextField1.setText("0");

        jButtonPolygonDeleteFirst.setText("Delete First");
        jButtonPolygonDeleteFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPolygonDeleteFirstActionPerformed(evt);
            }
        });

        jButtonPolygonDeleteLast.setText("Delete Last");
        jButtonPolygonDeleteLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPolygonDeleteLastActionPerformed(evt);
            }
        });

        jButtonPolygonDeleteAll.setText("Delete All");
        jButtonPolygonDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPolygonDeleteAllActionPerformed(evt);
            }
        });

        buttonGroupPolygon.add(jRadioButtonPolygonAddPoint);
        jRadioButtonPolygonAddPoint.setSelected(true);
        jRadioButtonPolygonAddPoint.setText("Add Point");

        buttonGroupPolygon.add(jRadioButtonPolygonMovePoint);
        jRadioButtonPolygonMovePoint.setText("Move Point");
        jRadioButtonPolygonMovePoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPolygonMovePointActionPerformed(evt);
            }
        });

        buttonGroupPolygon.add(jRadioButtonPolygonSetRotation);
        jRadioButtonPolygonSetRotation.setText("Drop Anchor");

        jLabel3.setText("Color Chooser:");

        jLabel4.setText("Visibility:");

        javax.swing.GroupLayout jPanelToolsPolygonLayout = new javax.swing.GroupLayout(jPanelToolsPolygon);
        jPanelToolsPolygon.setLayout(jPanelToolsPolygonLayout);
        jPanelToolsPolygonLayout.setHorizontalGroup(
            jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsPolygonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(colorChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxShowPolygon)
                        .addComponent(jCheckBoxShowPolygonRotation)
                        .addComponent(jCheckBoxShowAnchor)
                        .addGroup(jPanelToolsPolygonLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSliderRotatePolygon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelToolsPolygonLayout.createSequentialGroup()
                        .addComponent(jButtonPolygonDeleteFirst)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPolygonAddPoint))
                    .addGroup(jPanelToolsPolygonLayout.createSequentialGroup()
                        .addComponent(jButtonPolygonDeleteLast)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPolygonMovePoint))
                    .addGroup(jPanelToolsPolygonLayout.createSequentialGroup()
                        .addComponent(jButtonPolygonDeleteAll)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPolygonSetRotation))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelToolsPolygonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonPolygonDeleteAll, jButtonPolygonDeleteFirst, jButtonPolygonDeleteLast});

        jPanelToolsPolygonLayout.setVerticalGroup(
            jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsPolygonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jCheckBoxShowPolygon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowPolygonRotation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxShowAnchor)
                .addGap(18, 18, 18)
                .addGroup(jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderRotatePolygon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPolygonDeleteFirst)
                    .addComponent(jRadioButtonPolygonAddPoint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPolygonDeleteLast)
                    .addComponent(jRadioButtonPolygonMovePoint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPolygonDeleteAll)
                    .addComponent(jRadioButtonPolygonSetRotation))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanelToolsCurve.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsCurve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsCurve.setMaximumSize(new java.awt.Dimension(250, 630));
        jPanelToolsCurve.setPreferredSize(new java.awt.Dimension(250, 630));
        jPanelToolsCurve.setSize(new java.awt.Dimension(250, 630));

        jLabelCurve.setText("Curve");

        javax.swing.GroupLayout jPanelToolsCurveLayout = new javax.swing.GroupLayout(jPanelToolsCurve);
        jPanelToolsCurve.setLayout(jPanelToolsCurveLayout);
        jPanelToolsCurveLayout.setHorizontalGroup(
            jPanelToolsCurveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsCurveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCurve)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanelToolsCurveLayout.setVerticalGroup(
            jPanelToolsCurveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsCurveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCurve)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        jPanelToolsCompass.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsCompass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsCompass.setMaximumSize(new java.awt.Dimension(250, 630));
        jPanelToolsCompass.setPreferredSize(new java.awt.Dimension(250, 630));
        jPanelToolsCompass.setSize(new java.awt.Dimension(250, 630));

        jLabelCompass.setText("Compass");

        javax.swing.GroupLayout jPanelToolsCompassLayout = new javax.swing.GroupLayout(jPanelToolsCompass);
        jPanelToolsCompass.setLayout(jPanelToolsCompassLayout);
        jPanelToolsCompassLayout.setHorizontalGroup(
            jPanelToolsCompassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsCompassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompass)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanelToolsCompassLayout.setVerticalGroup(
            jPanelToolsCompassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsCompassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompass)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        jPanelToolsTheGrid.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsTheGrid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsTheGrid.setMaximumSize(new java.awt.Dimension(250, 630));
        jPanelToolsTheGrid.setPreferredSize(new java.awt.Dimension(250, 630));
        jPanelToolsTheGrid.setSize(new java.awt.Dimension(250, 630));

        jLabelTheGrid.setText("The Grid");

        javax.swing.GroupLayout jPanelToolsTheGridLayout = new javax.swing.GroupLayout(jPanelToolsTheGrid);
        jPanelToolsTheGrid.setLayout(jPanelToolsTheGridLayout);
        jPanelToolsTheGridLayout.setHorizontalGroup(
            jPanelToolsTheGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsTheGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTheGrid)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanelToolsTheGridLayout.setVerticalGroup(
            jPanelToolsTheGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsTheGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTheGrid)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        jLayeredPaneTools.setLayer(jPanelToolsClick, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneTools.setLayer(jPanelToolsMarker, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneTools.setLayer(jPanelToolsLine, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneTools.setLayer(jPanelToolsPolygon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneTools.setLayer(jPanelToolsCurve, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneTools.setLayer(jPanelToolsCompass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneTools.setLayer(jPanelToolsTheGrid, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneToolsLayout = new javax.swing.GroupLayout(jLayeredPaneTools);
        jLayeredPaneTools.setLayout(jLayeredPaneToolsLayout);
        jLayeredPaneToolsLayout.setHorizontalGroup(
            jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsMarker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsPolygon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsCurve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsCompass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsTheGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPaneToolsLayout.setVerticalGroup(
            jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsMarker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsPolygon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsCurve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsCompass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPaneToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPaneToolsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelToolsTheGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        theGrid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                theGridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                theGridFocusLost(evt);
            }
        });
        theGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                theGridMousePressed(evt);
            }
        });
        theGrid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                theGridKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout theGridLayout = new javax.swing.GroupLayout(theGrid);
        theGrid.setLayout(theGridLayout);
        theGridLayout.setHorizontalGroup(
            theGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        theGridLayout.setVerticalGroup(
            theGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPaneTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(theGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelToolSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelToolSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPaneTools)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(theGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClickActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsClick);
        
    }//GEN-LAST:event_jRadioButtonClickActionPerformed

    private void jRadioButtonMarkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMarkerActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsMarker);
    }//GEN-LAST:event_jRadioButtonMarkerActionPerformed

    private void jRadioButtonLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLineActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsLine);
    }//GEN-LAST:event_jRadioButtonLineActionPerformed

    private void jRadioButtonPolygonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPolygonActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsPolygon);
    }//GEN-LAST:event_jRadioButtonPolygonActionPerformed

    private void jRadioButtonCurveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCurveActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsCurve);
    }//GEN-LAST:event_jRadioButtonCurveActionPerformed

    private void jRadioButtonCompassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCompassActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsCompass);
    }//GEN-LAST:event_jRadioButtonCompassActionPerformed

    private void jRadioButtonTheGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTheGridActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsTheGrid);
    }//GEN-LAST:event_jRadioButtonTheGridActionPerformed

    private void jSliderZoomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderZoomStateChanged
        // TODO add your handling code here:
        Gridlines.setZoom(jSliderZoom.getValue());
        jTextFieldZoom.setText(Integer.toString(jSliderZoom.getValue()));
        theGrid.repaint();
    }//GEN-LAST:event_jSliderZoomStateChanged

    private void theGridMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theGridMousePressed
        // TODO add your handling code here:
       if(!theGrid.hasFocus()) {
            theGrid.requestFocus();
        }
        else {
            jTextFieldClickGridX.setText(String.valueOf(Gridlines.screenToGridX(evt.getX())));
            jTextFieldClickGridY.setText(String.valueOf(Gridlines.screenToGridY(evt.getY())));

            jTextFieldClickScreenX.setText(String.valueOf(evt.getX()));
            jTextFieldClickScreenY.setText(String.valueOf(evt.getY()));
            
            if(jRadioButtonClick.isSelected()) {
                
            }
            else if(jRadioButtonMarker.isSelected()) {
                
            }
            else if(jRadioButtonLine.isSelected()) {
                
            }
            else if(jRadioButtonPolygon.isSelected()) {
                clickPolygon(evt);
            }
            else if(jRadioButtonCurve.isSelected()) {
                
            }
            else if(jRadioButtonCompass.isSelected()) {
                
            }
       }
    }//GEN-LAST:event_theGridMousePressed
    private void clickPolygon(java.awt.event.MouseEvent evt) {
        //Left-Click
        if(evt.getButton() == MouseEvent.BUTTON1) {
            if(jRadioButtonPolygonMovePoint.isSelected()) {
                theGrid.polymorph.moveMarker(evt.getX(),evt.getY());
            }
            else if (jRadioButtonPolygonSetRotation.isSelected()) {
                theGrid.polymorphRotator.setAnchor(evt.getX(),evt.getY());
            }
            else {
                theGrid.polymorph.add(evt.getX(), evt.getY());   
            }
        }
        //Right-Click
        else if(evt.getButton() == MouseEvent.BUTTON3) {
            theGrid.polymorph.moveMarker(evt.getX(),evt.getY());
        }
        //Middle-Click
        else if(evt.getButton() == MouseEvent.BUTTON2) {
            theGrid.polymorphRotator.setAnchor(evt.getX(),evt.getY());
        }
        else {
            //Do Nothing.
        }
        theGrid.updatePolymorphRotator();
        theGrid.repaint();
    }
    
    private void theGridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_theGridKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_theGridKeyPressed

    private void theGridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_theGridFocusGained
        // TODO add your handling code here:
        theGrid.setBorder(gridFocused);
    }//GEN-LAST:event_theGridFocusGained

    private void theGridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_theGridFocusLost
        // TODO add your handling code here:
        theGrid.setBorder(gridUnFocused);
    }//GEN-LAST:event_theGridFocusLost

    private void jButtonPolygonDeleteFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPolygonDeleteFirstActionPerformed
        // TODO add your handling code here:
        theGrid.polymorph.removeFirst();
        theGrid.repaint();
    }//GEN-LAST:event_jButtonPolygonDeleteFirstActionPerformed

    private void jButtonPolygonDeleteLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPolygonDeleteLastActionPerformed
        // TODO add your handling code here:
        theGrid.polymorph.removeLast();
        theGrid.repaint();
    }//GEN-LAST:event_jButtonPolygonDeleteLastActionPerformed

    private void jButtonPolygonDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPolygonDeleteAllActionPerformed
        // TODO add your handling code here:
        theGrid.polymorph.clear();
        theGrid.repaint();
    }//GEN-LAST:event_jButtonPolygonDeleteAllActionPerformed

    private void jSliderRotatePolygonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRotatePolygonStateChanged
        // TODO add your handling code here:
        theGrid.polymorphRotator.setRotation((float)jSliderRotatePolygon.getValue());
        theGrid.repaint();
    }//GEN-LAST:event_jSliderRotatePolygonStateChanged

    private void jCheckBoxShowPolygonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPolygonActionPerformed
        // TODO add your handling code here:
        theGrid.polymorph.isVisible = jCheckBoxShowPolygon.isSelected();
        theGrid.repaint();
    }//GEN-LAST:event_jCheckBoxShowPolygonActionPerformed

    private void jCheckBoxShowPolygonRotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPolygonRotationActionPerformed
        // TODO add your handling code here:
        theGrid.polymorphRotator.isVisible = jCheckBoxShowPolygonRotation.isSelected();
        theGrid.repaint();
    }//GEN-LAST:event_jCheckBoxShowPolygonRotationActionPerformed

    private void jCheckBoxShowAnchorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowAnchorActionPerformed
        // TODO add your handling code here:
        theGrid.polymorphRotator.anchorIsVisible = jCheckBoxShowAnchor.isSelected();
        theGrid.repaint();
    }//GEN-LAST:event_jCheckBoxShowAnchorActionPerformed

    private void jRadioButtonPolygonMovePointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPolygonMovePointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPolygonMovePointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheGridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheGridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheGridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheGridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheGridGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPolygon;
    private javax.swing.ButtonGroup buttonGroupToolSelection;
    private com.hartgerink.thegrid3.ColorChooser colorChooser1;
    private javax.swing.JButton jButtonPolygonDeleteAll;
    private javax.swing.JButton jButtonPolygonDeleteFirst;
    private javax.swing.JButton jButtonPolygonDeleteLast;
    private javax.swing.JButton jButtonZeroLocation;
    private javax.swing.JCheckBox jCheckBoxShowAnchor;
    private javax.swing.JCheckBox jCheckBoxShowPolygon;
    private javax.swing.JCheckBox jCheckBoxShowPolygonRotation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClick;
    private javax.swing.JLabel jLabelClickGridY;
    private javax.swing.JLabel jLabelClickScreenX;
    private javax.swing.JLabel jLabelClickScreenY;
    private javax.swing.JLabel jLabelCompass;
    private javax.swing.JLabel jLabelCurve;
    private javax.swing.JLabel jLabelGridCoordinates;
    private javax.swing.JLabel jLabelGridY;
    private javax.swing.JLabel jLabelLastClickonGrid;
    private javax.swing.JLabel jLabelLine;
    private javax.swing.JLabel jLabelMarker;
    private javax.swing.JLabel jLabelTheGrid;
    private javax.swing.JLabel jLabelToolSelection;
    private javax.swing.JLabel jLabelZoom;
    private javax.swing.JLayeredPane jLayeredPaneTools;
    private javax.swing.JPanel jPanelNavigation;
    private javax.swing.JPanel jPanelToolSelection;
    private javax.swing.JPanel jPanelToolsClick;
    private javax.swing.JPanel jPanelToolsCompass;
    private javax.swing.JPanel jPanelToolsCurve;
    private javax.swing.JPanel jPanelToolsLine;
    private javax.swing.JPanel jPanelToolsMarker;
    private javax.swing.JPanel jPanelToolsPolygon;
    private javax.swing.JPanel jPanelToolsTheGrid;
    private javax.swing.JRadioButton jRadioButtonClick;
    private javax.swing.JRadioButton jRadioButtonCompass;
    private javax.swing.JRadioButton jRadioButtonCurve;
    private javax.swing.JRadioButton jRadioButtonLine;
    private javax.swing.JRadioButton jRadioButtonMarker;
    private javax.swing.JRadioButton jRadioButtonPolygon;
    private javax.swing.JRadioButton jRadioButtonPolygonAddPoint;
    private javax.swing.JRadioButton jRadioButtonPolygonMovePoint;
    private javax.swing.JRadioButton jRadioButtonPolygonSetRotation;
    private javax.swing.JRadioButton jRadioButtonTheGrid;
    private javax.swing.JSlider jSliderRotatePolygon;
    private javax.swing.JSlider jSliderZoom;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldClickGridX;
    private javax.swing.JTextField jTextFieldClickGridY;
    private javax.swing.JTextField jTextFieldClickScreenX;
    private javax.swing.JTextField jTextFieldClickScreenY;
    private javax.swing.JTextField jTextFieldGridX;
    private javax.swing.JTextField jTextFieldGridY;
    private javax.swing.JTextField jTextFieldZoom;
    private com.hartgerink.thegrid3.TheGrid theGrid;
    // End of variables declaration//GEN-END:variables
}
