/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hartgerink.thegrid3;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.border.LineBorder;

/**
 *
 * @author kevinhartgerink
 */
public class TheGridGUI extends javax.swing.JFrame {
    private LineBorder gridFocused;
    private LineBorder gridUnFocused;
    
    
    
    /**
     * Creates new form TheGrid
     */
    public TheGridGUI() {
        initComponents();

        //As the jLayeredPane adds jPanel(s), it sets the visiblity of those jPanel(s) to false.
        //To get the desired effect, we need all of them to be visible. This loop itererates though
        //each jPanel in the jLayeredPane and sets the visibility to true.
        for(int i=0; i<jLayeredPaneTools.getComponentCount(); i++) {
            jLayeredPaneTools.getComponent(i).setVisible(true);
        }
        for(int i=0; i<jLayeredPaneColor.getComponentCount(); i++) {
            jLayeredPaneColor.getComponent(i).setVisible(true);
        }
        
        jSliderRotatePolygon.setVisible(false);
        
        jRadioButtonPolygon.doClick();
        
        gridFocused = new LineBorder(Color.black, 3);
        gridUnFocused = new LineBorder(Color.lightGray, 3);   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupToolSelection = new javax.swing.ButtonGroup();
        buttonGroupPolygon = new javax.swing.ButtonGroup();
        jPanelGridCoordinates = new javax.swing.JPanel();
        jLabelGridCoordinates = new javax.swing.JLabel();
        jLabelGridX = new javax.swing.JLabel();
        jLabelGridY = new javax.swing.JLabel();
        jTextFieldGridX = new javax.swing.JTextField();
        jTextFieldGridY = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelNavigation = new javax.swing.JPanel();
        jSliderZoom = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldZoom = new javax.swing.JTextField();
        jLayeredPaneTools = new javax.swing.JLayeredPane();
        jPanelToolsClick = new javax.swing.JPanel();
        jLabelClick = new javax.swing.JLabel();
        jPanelToolsMarker = new javax.swing.JPanel();
        jLabelMarker = new javax.swing.JLabel();
        jPanelToolsLine = new javax.swing.JPanel();
        jLabelLine = new javax.swing.JLabel();
        jPanelToolsPolygon = new javax.swing.JPanel();
        jPanelPolygonRadioButtons = new javax.swing.JPanel();
        jRadioButtonPolygonAddPoint = new javax.swing.JRadioButton();
        jRadioButtonPolygonMovePoint = new javax.swing.JRadioButton();
        jRadioButtonPolygonSetRotation = new javax.swing.JRadioButton();
        jPanelPolygonButtons = new javax.swing.JPanel();
        jButtonPolygonDeleteFirst = new javax.swing.JButton();
        jButtonPolygonDeleteLast = new javax.swing.JButton();
        jButtonPolygonDeleteAll = new javax.swing.JButton();
        jPanelPolygonSettings = new javax.swing.JPanel();
        jSliderRotatePolygon = new javax.swing.JSlider();
        jCheckBoxShowPolygon = new javax.swing.JCheckBox();
        jCheckBoxShowPolygonRotation = new javax.swing.JCheckBox();
        jCheckBoxShowAnchor = new javax.swing.JCheckBox();
        jPanelToolsCurve = new javax.swing.JPanel();
        jLabelCurve = new javax.swing.JLabel();
        jPanelToolsCompass = new javax.swing.JPanel();
        jLabelCompass = new javax.swing.JLabel();
        jPanelToolsTheGrid = new javax.swing.JPanel();
        jLabelTheGrid = new javax.swing.JLabel();
        jPanelClickOnGrid = new javax.swing.JPanel();
        jLabelLastClickonGrid = new javax.swing.JLabel();
        jLabelClickGridX = new javax.swing.JLabel();
        jLabelClickGridY = new javax.swing.JLabel();
        jTextFieldClickGridX = new javax.swing.JTextField();
        jTextFieldClickGridY = new javax.swing.JTextField();
        jPanelClickOnScreen = new javax.swing.JPanel();
        jLabelLastClickonScreen = new javax.swing.JLabel();
        jLabelClickScreenX = new javax.swing.JLabel();
        jLabelClickScreenY = new javax.swing.JLabel();
        jTextFieldClickScreenX = new javax.swing.JTextField();
        jTextFieldClickScreenY = new javax.swing.JTextField();
        jPanelToolSelection = new javax.swing.JPanel();
        jLabelToolSelection = new javax.swing.JLabel();
        jRadioButtonClick = new javax.swing.JRadioButton();
        jRadioButtonMarker = new javax.swing.JRadioButton();
        jRadioButtonLine = new javax.swing.JRadioButton();
        jRadioButtonPolygon = new javax.swing.JRadioButton();
        jRadioButtonCurve = new javax.swing.JRadioButton();
        jRadioButtonCompass = new javax.swing.JRadioButton();
        jRadioButtonTheGrid = new javax.swing.JRadioButton();
        jLayeredPaneColor = new javax.swing.JLayeredPane();
        colorChooserPolygon = new com.hartgerink.thegrid3.ColorChooser();
        jPanelBlank = new javax.swing.JPanel();
        jLabelColorMessage = new javax.swing.JLabel();
        theGrid = new com.hartgerink.thegrid3.TheGrid();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGridCoordinates.setBackground(new java.awt.Color(153, 204, 255));
        jPanelGridCoordinates.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelGridCoordinates.setPreferredSize(new java.awt.Dimension(150, 110));
        jPanelGridCoordinates.setSize(new java.awt.Dimension(150, 110));

        jLabelGridCoordinates.setText("Grid Coordinates");

        jLabelGridX.setText("X:");

        jLabelGridY.setText("Y:");

        jTextFieldGridX.setColumns(4);
        jTextFieldGridX.setText("0");

        jTextFieldGridY.setColumns(4);
        jTextFieldGridY.setText("0");

        jButton1.setText("Zero");

        javax.swing.GroupLayout jPanelGridCoordinatesLayout = new javax.swing.GroupLayout(jPanelGridCoordinates);
        jPanelGridCoordinates.setLayout(jPanelGridCoordinatesLayout);
        jPanelGridCoordinatesLayout.setHorizontalGroup(
            jPanelGridCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGridCoordinatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGridCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGridCoordinatesLayout.createSequentialGroup()
                        .addComponent(jLabelGridX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGridX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanelGridCoordinatesLayout.createSequentialGroup()
                        .addGroup(jPanelGridCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGridCoordinates)
                            .addGroup(jPanelGridCoordinatesLayout.createSequentialGroup()
                                .addComponent(jLabelGridY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldGridY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelGridCoordinatesLayout.setVerticalGroup(
            jPanelGridCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGridCoordinatesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGridCoordinates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGridCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGridX)
                    .addComponent(jTextFieldGridX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGridCoordinatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGridY)
                    .addComponent(jTextFieldGridY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNavigation.setBackground(new java.awt.Color(153, 204, 255));
        jPanelNavigation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelNavigation.setPreferredSize(new java.awt.Dimension(240, 110));
        jPanelNavigation.setSize(new java.awt.Dimension(240, 110));

        jSliderZoom.setMinimum(1);
        jSliderZoom.setValue(20);
        jSliderZoom.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderZoomStateChanged(evt);
            }
        });

        jLabel1.setText("Zoom:");

        jTextFieldZoom.setColumns(3);
        jTextFieldZoom.setText("20");

        javax.swing.GroupLayout jPanelNavigationLayout = new javax.swing.GroupLayout(jPanelNavigation);
        jPanelNavigation.setLayout(jPanelNavigationLayout);
        jPanelNavigationLayout.setHorizontalGroup(
            jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNavigationLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNavigationLayout.setVerticalGroup(
            jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPaneTools.setMinimumSize(new java.awt.Dimension(500, 110));
        jLayeredPaneTools.setSize(new java.awt.Dimension(500, 110));
        jLayeredPaneTools.setLayout(new java.awt.CardLayout());

        jPanelToolsClick.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsClick.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsClick.setMinimumSize(new java.awt.Dimension(500, 110));
        jPanelToolsClick.setPreferredSize(new java.awt.Dimension(500, 110));
        jPanelToolsClick.setSize(new java.awt.Dimension(500, 110));

        jLabelClick.setText("Click");

        javax.swing.GroupLayout jPanelToolsClickLayout = new javax.swing.GroupLayout(jPanelToolsClick);
        jPanelToolsClick.setLayout(jPanelToolsClickLayout);
        jPanelToolsClickLayout.setHorizontalGroup(
            jPanelToolsClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsClickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClick)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanelToolsClickLayout.setVerticalGroup(
            jPanelToolsClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsClickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClick)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLayeredPaneTools.add(jPanelToolsClick, "card2");

        jPanelToolsMarker.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsMarker.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsMarker.setPreferredSize(new java.awt.Dimension(500, 110));
        jPanelToolsMarker.setSize(new java.awt.Dimension(500, 110));

        jLabelMarker.setText("Marker");

        javax.swing.GroupLayout jPanelToolsMarkerLayout = new javax.swing.GroupLayout(jPanelToolsMarker);
        jPanelToolsMarker.setLayout(jPanelToolsMarkerLayout);
        jPanelToolsMarkerLayout.setHorizontalGroup(
            jPanelToolsMarkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsMarkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMarker)
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanelToolsMarkerLayout.setVerticalGroup(
            jPanelToolsMarkerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsMarkerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMarker)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLayeredPaneTools.add(jPanelToolsMarker, "card3");

        jPanelToolsLine.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsLine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsLine.setPreferredSize(new java.awt.Dimension(500, 110));
        jPanelToolsLine.setSize(new java.awt.Dimension(500, 110));

        jLabelLine.setText("Line");

        javax.swing.GroupLayout jPanelToolsLineLayout = new javax.swing.GroupLayout(jPanelToolsLine);
        jPanelToolsLine.setLayout(jPanelToolsLineLayout);
        jPanelToolsLineLayout.setHorizontalGroup(
            jPanelToolsLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsLineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLine)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        jPanelToolsLineLayout.setVerticalGroup(
            jPanelToolsLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsLineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLine)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLayeredPaneTools.add(jPanelToolsLine, "card4");

        jPanelToolsPolygon.setBackground(java.awt.Color.white);
        jPanelToolsPolygon.setPreferredSize(new java.awt.Dimension(500, 110));
        jPanelToolsPolygon.setSize(new java.awt.Dimension(500, 110));

        jPanelPolygonRadioButtons.setBackground(new java.awt.Color(153, 204, 255));
        jPanelPolygonRadioButtons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroupPolygon.add(jRadioButtonPolygonAddPoint);
        jRadioButtonPolygonAddPoint.setSelected(true);
        jRadioButtonPolygonAddPoint.setText("Add Point");

        buttonGroupPolygon.add(jRadioButtonPolygonMovePoint);
        jRadioButtonPolygonMovePoint.setText("Move Point");

        buttonGroupPolygon.add(jRadioButtonPolygonSetRotation);
        jRadioButtonPolygonSetRotation.setText("Drop Anchor");

        javax.swing.GroupLayout jPanelPolygonRadioButtonsLayout = new javax.swing.GroupLayout(jPanelPolygonRadioButtons);
        jPanelPolygonRadioButtons.setLayout(jPanelPolygonRadioButtonsLayout);
        jPanelPolygonRadioButtonsLayout.setHorizontalGroup(
            jPanelPolygonRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPolygonRadioButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPolygonRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPolygonAddPoint)
                    .addComponent(jRadioButtonPolygonMovePoint)
                    .addComponent(jRadioButtonPolygonSetRotation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPolygonRadioButtonsLayout.setVerticalGroup(
            jPanelPolygonRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPolygonRadioButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonPolygonAddPoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPolygonMovePoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPolygonSetRotation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPolygonButtons.setBackground(new java.awt.Color(153, 204, 255));
        jPanelPolygonButtons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonPolygonDeleteFirst.setText("Delete First");
        jButtonPolygonDeleteFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPolygonDeleteFirstActionPerformed(evt);
            }
        });

        jButtonPolygonDeleteLast.setText("Delete Last");
        jButtonPolygonDeleteLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPolygonDeleteLastActionPerformed(evt);
            }
        });

        jButtonPolygonDeleteAll.setText("Delete All");
        jButtonPolygonDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPolygonDeleteAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPolygonButtonsLayout = new javax.swing.GroupLayout(jPanelPolygonButtons);
        jPanelPolygonButtons.setLayout(jPanelPolygonButtonsLayout);
        jPanelPolygonButtonsLayout.setHorizontalGroup(
            jPanelPolygonButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPolygonButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPolygonButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPolygonButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonPolygonDeleteFirst)
                        .addComponent(jButtonPolygonDeleteLast))
                    .addComponent(jButtonPolygonDeleteAll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPolygonButtonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonPolygonDeleteAll, jButtonPolygonDeleteFirst, jButtonPolygonDeleteLast});

        jPanelPolygonButtonsLayout.setVerticalGroup(
            jPanelPolygonButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPolygonButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPolygonDeleteFirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPolygonDeleteLast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPolygonDeleteAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPolygonSettings.setBackground(new java.awt.Color(153, 204, 255));
        jPanelPolygonSettings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSliderRotatePolygon.setMaximum(360);
        jSliderRotatePolygon.setValue(0);
        jSliderRotatePolygon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRotatePolygonStateChanged(evt);
            }
        });

        jCheckBoxShowPolygon.setSelected(true);
        jCheckBoxShowPolygon.setText("Show Polygon");
        jCheckBoxShowPolygon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPolygonActionPerformed(evt);
            }
        });

        jCheckBoxShowPolygonRotation.setText("Show Rotation");
        jCheckBoxShowPolygonRotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPolygonRotationActionPerformed(evt);
            }
        });

        jCheckBoxShowAnchor.setText("Show Anchor");
        jCheckBoxShowAnchor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowAnchorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPolygonSettingsLayout = new javax.swing.GroupLayout(jPanelPolygonSettings);
        jPanelPolygonSettings.setLayout(jPanelPolygonSettingsLayout);
        jPanelPolygonSettingsLayout.setHorizontalGroup(
            jPanelPolygonSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPolygonSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPolygonSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPolygonSettingsLayout.createSequentialGroup()
                        .addComponent(jCheckBoxShowPolygonRotation)
                        .addGap(18, 102, Short.MAX_VALUE))
                    .addGroup(jPanelPolygonSettingsLayout.createSequentialGroup()
                        .addGroup(jPanelPolygonSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxShowAnchor)
                            .addComponent(jCheckBoxShowPolygon))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSliderRotatePolygon, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPolygonSettingsLayout.setVerticalGroup(
            jPanelPolygonSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPolygonSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxShowPolygon)
                .addGap(0, 0, 0)
                .addComponent(jCheckBoxShowPolygonRotation)
                .addGap(0, 0, 0)
                .addComponent(jCheckBoxShowAnchor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderRotatePolygon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelToolsPolygonLayout = new javax.swing.GroupLayout(jPanelToolsPolygon);
        jPanelToolsPolygon.setLayout(jPanelToolsPolygonLayout);
        jPanelToolsPolygonLayout.setHorizontalGroup(
            jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsPolygonLayout.createSequentialGroup()
                .addComponent(jPanelPolygonRadioButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelPolygonButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelPolygonSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelToolsPolygonLayout.setVerticalGroup(
            jPanelToolsPolygonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPolygonRadioButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPolygonButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPolygonSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPaneTools.add(jPanelToolsPolygon, "card5");

        jPanelToolsCurve.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsCurve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsCurve.setPreferredSize(new java.awt.Dimension(500, 110));
        jPanelToolsCurve.setSize(new java.awt.Dimension(500, 110));

        jLabelCurve.setText("Curve");

        javax.swing.GroupLayout jPanelToolsCurveLayout = new javax.swing.GroupLayout(jPanelToolsCurve);
        jPanelToolsCurve.setLayout(jPanelToolsCurveLayout);
        jPanelToolsCurveLayout.setHorizontalGroup(
            jPanelToolsCurveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsCurveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCurve)
                .addContainerGap(454, Short.MAX_VALUE))
        );
        jPanelToolsCurveLayout.setVerticalGroup(
            jPanelToolsCurveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsCurveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCurve)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLayeredPaneTools.add(jPanelToolsCurve, "card6");

        jPanelToolsCompass.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsCompass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsCompass.setPreferredSize(new java.awt.Dimension(500, 110));
        jPanelToolsCompass.setSize(new java.awt.Dimension(500, 110));

        jLabelCompass.setText("Compass");

        javax.swing.GroupLayout jPanelToolsCompassLayout = new javax.swing.GroupLayout(jPanelToolsCompass);
        jPanelToolsCompass.setLayout(jPanelToolsCompassLayout);
        jPanelToolsCompassLayout.setHorizontalGroup(
            jPanelToolsCompassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsCompassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompass)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanelToolsCompassLayout.setVerticalGroup(
            jPanelToolsCompassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsCompassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompass)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLayeredPaneTools.add(jPanelToolsCompass, "card7");

        jPanelToolsTheGrid.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolsTheGrid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolsTheGrid.setPreferredSize(new java.awt.Dimension(500, 110));
        jPanelToolsTheGrid.setSize(new java.awt.Dimension(500, 110));

        jLabelTheGrid.setText("The Grid");

        javax.swing.GroupLayout jPanelToolsTheGridLayout = new javax.swing.GroupLayout(jPanelToolsTheGrid);
        jPanelToolsTheGrid.setLayout(jPanelToolsTheGridLayout);
        jPanelToolsTheGridLayout.setHorizontalGroup(
            jPanelToolsTheGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsTheGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTheGrid)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        jPanelToolsTheGridLayout.setVerticalGroup(
            jPanelToolsTheGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolsTheGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTheGrid)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLayeredPaneTools.add(jPanelToolsTheGrid, "card7");

        jPanelClickOnGrid.setBackground(new java.awt.Color(153, 204, 255));
        jPanelClickOnGrid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelClickOnGrid.setPreferredSize(new java.awt.Dimension(150, 96));
        jPanelClickOnGrid.setSize(new java.awt.Dimension(150, 96));

        jLabelLastClickonGrid.setText("Last Click on Grid");

        jLabelClickGridX.setText("X:");

        jLabelClickGridY.setText("Y:");

        jTextFieldClickGridX.setColumns(4);
        jTextFieldClickGridX.setText("0");

        jTextFieldClickGridY.setColumns(4);
        jTextFieldClickGridY.setText("0");

        javax.swing.GroupLayout jPanelClickOnGridLayout = new javax.swing.GroupLayout(jPanelClickOnGrid);
        jPanelClickOnGrid.setLayout(jPanelClickOnGridLayout);
        jPanelClickOnGridLayout.setHorizontalGroup(
            jPanelClickOnGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClickOnGridLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClickOnGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLastClickonGrid)
                    .addGroup(jPanelClickOnGridLayout.createSequentialGroup()
                        .addComponent(jLabelClickGridX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClickGridX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClickOnGridLayout.createSequentialGroup()
                        .addComponent(jLabelClickGridY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClickGridY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelClickOnGridLayout.setVerticalGroup(
            jPanelClickOnGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClickOnGridLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLastClickonGrid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClickOnGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClickGridX)
                    .addComponent(jTextFieldClickGridX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClickOnGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClickGridY)
                    .addComponent(jTextFieldClickGridY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelClickOnScreen.setBackground(new java.awt.Color(153, 204, 255));
        jPanelClickOnScreen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelLastClickonScreen.setText("Last Click on Screen");

        jLabelClickScreenX.setText("X:");

        jLabelClickScreenY.setText("Y:");

        jTextFieldClickScreenX.setColumns(4);
        jTextFieldClickScreenX.setText("0");

        jTextFieldClickScreenY.setColumns(4);
        jTextFieldClickScreenY.setText("0");

        javax.swing.GroupLayout jPanelClickOnScreenLayout = new javax.swing.GroupLayout(jPanelClickOnScreen);
        jPanelClickOnScreen.setLayout(jPanelClickOnScreenLayout);
        jPanelClickOnScreenLayout.setHorizontalGroup(
            jPanelClickOnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClickOnScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClickOnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLastClickonScreen)
                    .addGroup(jPanelClickOnScreenLayout.createSequentialGroup()
                        .addComponent(jLabelClickScreenX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClickScreenX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClickOnScreenLayout.createSequentialGroup()
                        .addComponent(jLabelClickScreenY)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClickScreenY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanelClickOnScreenLayout.setVerticalGroup(
            jPanelClickOnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClickOnScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLastClickonScreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClickOnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClickScreenX)
                    .addComponent(jTextFieldClickScreenX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClickOnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClickScreenY)
                    .addComponent(jTextFieldClickScreenY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelToolSelection.setBackground(new java.awt.Color(153, 204, 255));
        jPanelToolSelection.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelToolSelection.setPreferredSize(new java.awt.Dimension(150, 235));

        jLabelToolSelection.setText("Tool Selection");

        buttonGroupToolSelection.add(jRadioButtonClick);
        jRadioButtonClick.setText("Click");
        jRadioButtonClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClickActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonMarker);
        jRadioButtonMarker.setText("Marker");
        jRadioButtonMarker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMarkerActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonLine);
        jRadioButtonLine.setText("Line");
        jRadioButtonLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLineActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonPolygon);
        jRadioButtonPolygon.setText("Polygon");
        jRadioButtonPolygon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPolygonActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonCurve);
        jRadioButtonCurve.setText("Curve");
        jRadioButtonCurve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCurveActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonCompass);
        jRadioButtonCompass.setText("Compass");
        jRadioButtonCompass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompassActionPerformed(evt);
            }
        });

        buttonGroupToolSelection.add(jRadioButtonTheGrid);
        jRadioButtonTheGrid.setText("The Grid");
        jRadioButtonTheGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTheGridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolSelectionLayout = new javax.swing.GroupLayout(jPanelToolSelection);
        jPanelToolSelection.setLayout(jPanelToolSelectionLayout);
        jPanelToolSelectionLayout.setHorizontalGroup(
            jPanelToolSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelToolSelection)
                    .addComponent(jRadioButtonClick)
                    .addComponent(jRadioButtonMarker)
                    .addComponent(jRadioButtonLine)
                    .addComponent(jRadioButtonPolygon)
                    .addComponent(jRadioButtonCurve)
                    .addComponent(jRadioButtonCompass)
                    .addComponent(jRadioButtonTheGrid))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanelToolSelectionLayout.setVerticalGroup(
            jPanelToolSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToolSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonClick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMarker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPolygon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCurve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCompass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTheGrid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPaneColor.setLayout(new java.awt.CardLayout());

        colorChooserPolygon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                colorChooserPolygonPropertyChange(evt);
            }
        });
        jLayeredPaneColor.add(colorChooserPolygon, "card2");

        jPanelBlank.setBackground(new java.awt.Color(153, 204, 255));
        jPanelBlank.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelBlank.setPreferredSize(new java.awt.Dimension(359, 121));

        jLabelColorMessage.setText("There are no color options.");

        javax.swing.GroupLayout jPanelBlankLayout = new javax.swing.GroupLayout(jPanelBlank);
        jPanelBlank.setLayout(jPanelBlankLayout);
        jPanelBlankLayout.setHorizontalGroup(
            jPanelBlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelColorMessage)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanelBlankLayout.setVerticalGroup(
            jPanelBlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelColorMessage)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jLayeredPaneColor.add(jPanelBlank, "card3");

        theGrid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                theGridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                theGridFocusLost(evt);
            }
        });
        theGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                theGridMousePressed(evt);
            }
        });
        theGrid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                theGridKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout theGridLayout = new javax.swing.GroupLayout(theGrid);
        theGrid.setLayout(theGridLayout);
        theGridLayout.setHorizontalGroup(
            theGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        theGridLayout.setVerticalGroup(
            theGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");
        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelGridCoordinates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPaneTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPaneColor))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanelClickOnScreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelClickOnGrid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanelToolSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(theGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPaneColor)
                    .addComponent(jLayeredPaneTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGridCoordinates, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jPanelNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelClickOnGrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelClickOnScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelToolSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addComponent(theGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonClickActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsClick);
        jLayeredPaneColor.moveToFront(jPanelBlank);
        
    }//GEN-LAST:event_jRadioButtonClickActionPerformed

    private void jRadioButtonMarkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMarkerActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsMarker);
        jLayeredPaneColor.moveToFront(jPanelBlank);
    }//GEN-LAST:event_jRadioButtonMarkerActionPerformed

    private void jRadioButtonLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLineActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsLine);
        jLayeredPaneColor.moveToFront(jPanelBlank);
    }//GEN-LAST:event_jRadioButtonLineActionPerformed

    private void jRadioButtonPolygonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPolygonActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsPolygon);
        jLayeredPaneColor.moveToFront(colorChooserPolygon);
    }//GEN-LAST:event_jRadioButtonPolygonActionPerformed

    private void jRadioButtonCurveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCurveActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsCurve);
        jLayeredPaneColor.moveToFront(jPanelBlank);
    }//GEN-LAST:event_jRadioButtonCurveActionPerformed

    private void jRadioButtonCompassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCompassActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsCompass);
        jLayeredPaneColor.moveToFront(jPanelBlank);
    }//GEN-LAST:event_jRadioButtonCompassActionPerformed

    private void jRadioButtonTheGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTheGridActionPerformed
        // TODO add your handling code here:
        jLayeredPaneTools.moveToFront(jPanelToolsTheGrid);
        jLayeredPaneColor.moveToFront(jPanelBlank);
    }//GEN-LAST:event_jRadioButtonTheGridActionPerformed

    private void jSliderZoomStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderZoomStateChanged
        // TODO add your handling code here:
        Gridlines.setZoom(jSliderZoom.getValue());
        jTextFieldZoom.setText(Integer.toString(jSliderZoom.getValue()));
        theGrid.repaint();
    }//GEN-LAST:event_jSliderZoomStateChanged

    private void theGridMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theGridMousePressed
        // TODO add your handling code here:
       if(!theGrid.hasFocus()) {
            theGrid.requestFocus();
        }
        else {
            jTextFieldClickGridX.setText(String.valueOf(Gridlines.screenToGridX(evt.getX())));
            jTextFieldClickGridY.setText(String.valueOf(Gridlines.screenToGridY(evt.getY())));

            jTextFieldClickScreenX.setText(String.valueOf(evt.getX()));
            jTextFieldClickScreenY.setText(String.valueOf(evt.getY()));
            
            if(jRadioButtonClick.isSelected()) {
                
            }
            else if(jRadioButtonMarker.isSelected()) {
                
            }
            else if(jRadioButtonLine.isSelected()) {
                
            }
            else if(jRadioButtonPolygon.isSelected()) {
                clickPolygon(evt);
            }
            else if(jRadioButtonCurve.isSelected()) {
                
            }
            else if(jRadioButtonCompass.isSelected()) {
                
            }
       }
    }//GEN-LAST:event_theGridMousePressed
    private void clickPolygon(java.awt.event.MouseEvent evt) {
        //Left-Click
        if(evt.getButton() == MouseEvent.BUTTON1) {
            if(jRadioButtonPolygonMovePoint.isSelected()) {
                theGrid.polymorph.moveMarker(evt.getX(),evt.getY());
            }
            else if (jRadioButtonPolygonSetRotation.isSelected()) {
                theGrid.polymorphRotator.setAnchor(evt.getX(),evt.getY());
            }
            else {
                theGrid.polymorph.add(evt.getX(), evt.getY());   
            }
        }
        //Right-Click
        else if(evt.getButton() == MouseEvent.BUTTON3) {
            theGrid.polymorph.moveMarker(evt.getX(),evt.getY());
        }
        //Middle-Click
        else if(evt.getButton() == MouseEvent.BUTTON2) {
            theGrid.polymorphRotator.setAnchor(evt.getX(),evt.getY());
        }
        else {
            //Do Nothing.
        }
        theGrid.updatePolymorphRotator();
        theGrid.repaint();
    }
    
    private void theGridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_theGridKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_theGridKeyPressed

    private void theGridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_theGridFocusGained
        // TODO add your handling code here:
        theGrid.setBorder(gridFocused);
    }//GEN-LAST:event_theGridFocusGained

    private void theGridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_theGridFocusLost
        // TODO add your handling code here:
        theGrid.setBorder(gridUnFocused);
    }//GEN-LAST:event_theGridFocusLost

    private void colorChooserPolygonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_colorChooserPolygonPropertyChange
        // TODO add your handling code here:
        theGrid.polymorph.setColor(colorChooserPolygon.getColor());
        theGrid.repaint();
    }//GEN-LAST:event_colorChooserPolygonPropertyChange

    private void jButtonPolygonDeleteFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPolygonDeleteFirstActionPerformed
        // TODO add your handling code here:
        theGrid.polymorph.removeFirst();
        theGrid.repaint();
    }//GEN-LAST:event_jButtonPolygonDeleteFirstActionPerformed

    private void jButtonPolygonDeleteLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPolygonDeleteLastActionPerformed
        // TODO add your handling code here:
        theGrid.polymorph.removeLast();
        theGrid.repaint();
    }//GEN-LAST:event_jButtonPolygonDeleteLastActionPerformed

    private void jButtonPolygonDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPolygonDeleteAllActionPerformed
        // TODO add your handling code here:
        theGrid.polymorph.clear();
        theGrid.repaint();
    }//GEN-LAST:event_jButtonPolygonDeleteAllActionPerformed

    private void jSliderRotatePolygonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRotatePolygonStateChanged
        // TODO add your handling code here:
        theGrid.polymorphRotator.setRotation((float)jSliderRotatePolygon.getValue());
        theGrid.repaint();
    }//GEN-LAST:event_jSliderRotatePolygonStateChanged

    private void jCheckBoxShowPolygonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPolygonActionPerformed
        // TODO add your handling code here:
        theGrid.polymorph.isVisible = jCheckBoxShowPolygon.isSelected();
        theGrid.repaint();
    }//GEN-LAST:event_jCheckBoxShowPolygonActionPerformed

    private void jCheckBoxShowPolygonRotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPolygonRotationActionPerformed
        // TODO add your handling code here:
        theGrid.polymorphRotator.isVisible = jCheckBoxShowPolygonRotation.isSelected();
        jSliderRotatePolygon.setVisible(jCheckBoxShowPolygonRotation.isSelected());
        theGrid.repaint();
    }//GEN-LAST:event_jCheckBoxShowPolygonRotationActionPerformed

    private void jCheckBoxShowAnchorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowAnchorActionPerformed
        // TODO add your handling code here:
        theGrid.polymorphRotator.anchorIsVisible = jCheckBoxShowAnchor.isSelected();
        theGrid.repaint();
    }//GEN-LAST:event_jCheckBoxShowAnchorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheGridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheGridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheGridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheGridGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheGridGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPolygon;
    private javax.swing.ButtonGroup buttonGroupToolSelection;
    private com.hartgerink.thegrid3.ColorChooser colorChooserPolygon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPolygonDeleteAll;
    private javax.swing.JButton jButtonPolygonDeleteFirst;
    private javax.swing.JButton jButtonPolygonDeleteLast;
    private javax.swing.JCheckBox jCheckBoxShowAnchor;
    private javax.swing.JCheckBox jCheckBoxShowPolygon;
    private javax.swing.JCheckBox jCheckBoxShowPolygonRotation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClick;
    private javax.swing.JLabel jLabelClickGridX;
    private javax.swing.JLabel jLabelClickGridY;
    private javax.swing.JLabel jLabelClickScreenX;
    private javax.swing.JLabel jLabelClickScreenY;
    private javax.swing.JLabel jLabelColorMessage;
    private javax.swing.JLabel jLabelCompass;
    private javax.swing.JLabel jLabelCurve;
    private javax.swing.JLabel jLabelGridCoordinates;
    private javax.swing.JLabel jLabelGridX;
    private javax.swing.JLabel jLabelGridY;
    private javax.swing.JLabel jLabelLastClickonGrid;
    private javax.swing.JLabel jLabelLastClickonScreen;
    private javax.swing.JLabel jLabelLine;
    private javax.swing.JLabel jLabelMarker;
    private javax.swing.JLabel jLabelTheGrid;
    private javax.swing.JLabel jLabelToolSelection;
    private javax.swing.JLayeredPane jLayeredPaneColor;
    private javax.swing.JLayeredPane jLayeredPaneTools;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JPanel jPanelBlank;
    private javax.swing.JPanel jPanelClickOnGrid;
    private javax.swing.JPanel jPanelClickOnScreen;
    private javax.swing.JPanel jPanelGridCoordinates;
    private javax.swing.JPanel jPanelNavigation;
    private javax.swing.JPanel jPanelPolygonButtons;
    private javax.swing.JPanel jPanelPolygonRadioButtons;
    private javax.swing.JPanel jPanelPolygonSettings;
    private javax.swing.JPanel jPanelToolSelection;
    private javax.swing.JPanel jPanelToolsClick;
    private javax.swing.JPanel jPanelToolsCompass;
    private javax.swing.JPanel jPanelToolsCurve;
    private javax.swing.JPanel jPanelToolsLine;
    private javax.swing.JPanel jPanelToolsMarker;
    private javax.swing.JPanel jPanelToolsPolygon;
    private javax.swing.JPanel jPanelToolsTheGrid;
    private javax.swing.JRadioButton jRadioButtonClick;
    private javax.swing.JRadioButton jRadioButtonCompass;
    private javax.swing.JRadioButton jRadioButtonCurve;
    private javax.swing.JRadioButton jRadioButtonLine;
    private javax.swing.JRadioButton jRadioButtonMarker;
    private javax.swing.JRadioButton jRadioButtonPolygon;
    private javax.swing.JRadioButton jRadioButtonPolygonAddPoint;
    private javax.swing.JRadioButton jRadioButtonPolygonMovePoint;
    private javax.swing.JRadioButton jRadioButtonPolygonSetRotation;
    private javax.swing.JRadioButton jRadioButtonTheGrid;
    private javax.swing.JSlider jSliderRotatePolygon;
    private javax.swing.JSlider jSliderZoom;
    private javax.swing.JTextField jTextFieldClickGridX;
    private javax.swing.JTextField jTextFieldClickGridY;
    private javax.swing.JTextField jTextFieldClickScreenX;
    private javax.swing.JTextField jTextFieldClickScreenY;
    private javax.swing.JTextField jTextFieldGridX;
    private javax.swing.JTextField jTextFieldGridY;
    private javax.swing.JTextField jTextFieldZoom;
    private com.hartgerink.thegrid3.TheGrid theGrid;
    // End of variables declaration//GEN-END:variables
}
